services:
  - type: web
    name: dsa-llm-backend
    runtime: docker
    repo: https://github.com/SohaibSajid56/LLM-By-Sohaib
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
