services:
  - type: web
    name: dsa-llm-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: static
    name: dsa-llm-frontend
    rootDir: public
    buildCommand: ""
    staticPublishPath: public
